// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHost(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddHost'](arg1, arg2, arg3, arg4);
}

export function AssistantAsk(arg1) {
  return window['go']['main']['App']['AssistantAsk'](arg1);
}

export function AssistantAvailable() {
  return window['go']['main']['App']['AssistantAvailable']();
}

export function AssistantCancel(arg1) {
  return window['go']['main']['App']['AssistantCancel'](arg1);
}

export function AssistantConfirm(arg1) {
  return window['go']['main']['App']['AssistantConfirm'](arg1);
}

export function AssistantEnabled() {
  return window['go']['main']['App']['AssistantEnabled']();
}

export function AssistantHistory() {
  return window['go']['main']['App']['AssistantHistory']();
}

export function AssistantReset() {
  return window['go']['main']['App']['AssistantReset']();
}

export function Attach(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Attach'](arg1, arg2, arg3, arg4);
}

export function ClientOp(arg1, arg2, arg3) {
  return window['go']['main']['App']['ClientOp'](arg1, arg2, arg3);
}

export function ClientOpAll(arg1, arg2) {
  return window['go']['main']['App']['ClientOpAll'](arg1, arg2);
}

export function DetectDaemon() {
  return window['go']['main']['App']['DetectDaemon']();
}

export function FmtAgo(arg1) {
  return window['go']['main']['App']['FmtAgo'](arg1);
}

export function FmtBytes(arg1) {
  return window['go']['main']['App']['FmtBytes'](arg1);
}

export function FmtCredit(arg1) {
  return window['go']['main']['App']['FmtCredit'](arg1);
}

export function FmtDuration(arg1) {
  return window['go']['main']['App']['FmtDuration'](arg1);
}

export function FmtTime(arg1) {
  return window['go']['main']['App']['FmtTime'](arg1);
}

export function GetAllSnapshots() {
  return window['go']['main']['App']['GetAllSnapshots']();
}

export function GetDaemonStatus() {
  return window['go']['main']['App']['GetDaemonStatus']();
}

export function GetDiskUsage(arg1) {
  return window['go']['main']['App']['GetDiskUsage'](arg1);
}

export function GetEnergy(arg1) {
  return window['go']['main']['App']['GetEnergy'](arg1);
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetHostInfo() {
  return window['go']['main']['App']['GetHostInfo']();
}

export function GetHosts() {
  return window['go']['main']['App']['GetHosts']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLanguages() {
  return window['go']['main']['App']['GetLanguages']();
}

export function GetPrefs(arg1) {
  return window['go']['main']['App']['GetPrefs'](arg1);
}

export function GetProjectCatalog() {
  return window['go']['main']['App']['GetProjectCatalog']();
}

export function GetProjectConfig(arg1) {
  return window['go']['main']['App']['GetProjectConfig'](arg1);
}

export function GetSnapshot(arg1) {
  return window['go']['main']['App']['GetSnapshot'](arg1);
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}

export function GetTranslations(arg1) {
  return window['go']['main']['App']['GetTranslations'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetXferHistory(arg1) {
  return window['go']['main']['App']['GetXferHistory'](arg1);
}

export function LookupAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['LookupAccount'](arg1, arg2, arg3);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ProjColor(arg1) {
  return window['go']['main']['App']['ProjColor'](arg1);
}

export function ProjectOp(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProjectOp'](arg1, arg2, arg3);
}

export function RefreshAll() {
  return window['go']['main']['App']['RefreshAll']();
}

export function RemoveHost(arg1) {
  return window['go']['main']['App']['RemoveHost'](arg1);
}

export function SetAssistantEnabled(arg1) {
  return window['go']['main']['App']['SetAssistantEnabled'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetPrefs(arg1, arg2) {
  return window['go']['main']['App']['SetPrefs'](arg1, arg2);
}

export function StartDaemon() {
  return window['go']['main']['App']['StartDaemon']();
}

export function StopDaemon() {
  return window['go']['main']['App']['StopDaemon']();
}

export function TaskOp(arg1, arg2, arg3) {
  return window['go']['main']['App']['TaskOp'](arg1, arg2, arg3);
}

export function TestHost(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestHost'](arg1, arg2, arg3);
}

export function TransferOp(arg1, arg2, arg3) {
  return window['go']['main']['App']['TransferOp'](arg1, arg2, arg3);
}

export function UpdateHost(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateHost'](arg1, arg2, arg3, arg4, arg5);
}
